### ISSUE TITLE
Request to Develop Attacker Information Collection Feature for DeauthDetector

### ISSUE THREAD

**Issue by Droid-MAX** [spacehuhn/DeauthDetector#8]
Hope to develop more sophisticated detection and attacker information collection capabilities for DeauthDetector, If the hardware system of esp8266 itself is not able to do it, then close this issue, thanks!

**Comment by Hitanshu774** [comment]
I am very glad to try to developer attacker information collection feature
for deauthdetector but I don't have esp8266 development board on which I
can work.

I request you to please provide me those chip set to developer it.
